// ===== 行程数据 =====
const DAYS_DATA = [
  {
    id:1, date:'5月1日', weekday:'周五', city:'✈️ → 罗马', cityTag:'罗马',
    title:'抵达罗马 + 初探', theme:'长途飞行后轻松漫步，感受罗马夜色',
    emoji:'✈️', color:'#E85D3A',
    bannerGradient:'linear-gradient(135deg,#FF6B6B,#E85D3A)',
    route:['FCO机场','Leonardo Express','Roma Termini','酒店','西班牙广场','许愿池','晚餐'],
    mapCenter:[41.9028,12.4964], mapZoom:14,
    spots:[
      {lat:41.9060,lng:12.4833,name:'西班牙广场',num:'❶'},
      {lat:41.9009,lng:12.4833,name:'许愿池',num:'❷'},
    ],
    timeline:[
      {time:'13:25',type:'transport',title:'✈️ 抵达FCO机场',desc:'过海关取行李约需1小时'},
      {time:'15:00',type:'transport',title:'🚂 Leonardo Express',desc:'€14/人，32分钟直达Roma Termini',
        detail:{emoji:'🚂',name:'Leonardo Express 机场快线',subtitle:'FCO → Roma Termini',
          info:[{label:'票价',value:'€14/人'},{label:'用时',value:'32分钟'},{label:'频次',value:'每15-30分钟'},{label:'推荐',value:'⭐⭐⭐⭐⭐'}],
          highlights:['直达Roma Termini无需换乘','跟随机场"Train"标志找到','可Trenitalia官网或现场自助机购票','携程购买支付宝支付更方便'],
          warnings:['落地后约14:30出关，赶15:00左右班次'],photos:[]}},
      {time:'16:00',type:'default',title:'🏨 入住酒店休整',desc:'推荐住Termini火车站附近或历史中心区'},
      {time:'16:30',type:'sight',title:'🏛️ 西班牙广场',desc:'《罗马假日》赫本同款！台阶、破船喷泉、购物街',
        detail:{emoji:'🏛️',name:'西班牙广场',subtitle:'Piazza di Spagna · 免费',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'30-45分钟'},{label:'最佳时间',value:'下午/傍晚'},{label:'附近',value:'奢侈品购物街'}],
          history:{
            summary:'西班牙广场因毗邻西班牙驻教廷大使馆而得名，是18世纪罗马最时尚的社交中心。',
            facts:[
              {label:'建造',value:'西班牙台阶建于1723-1725年，由建筑师弗朗切斯科·德·桑克蒂斯设计'},
              {label:'名称',value:'广场以西班牙驻教廷大使馆命名，台阶则由法国资助建造'},
              {label:'破船喷泉',value:'台阶下方的"破船喷泉"（Fontana della Barcaccia）由贝尼尼父子于1627-1629年设计'},
              {label:'文化',value:'18-19世纪是英国诗人济慈、拜伦等文人聚集地，济慈在此度过生命最后时光'},
            ],
            description:'西班牙台阶共135级，连接山下的西班牙广场和山上的三位一体教堂。1953年奥黛丽·赫本在《罗马假日》中在台阶上吃冰淇淋的场景让这里闻名世界。如今广场周围是罗马最高端的购物区，Via Condotti汇聚了众多国际奢侈品牌。'
          },
          highlights:['《罗马假日》经典取景地，赫本吃冰淇淋的台阶','台阶共135级，顶端是三位一体教堂','台阶下方是破船喷泉','附近Via del Corso是主要购物街，Gucci/Prada等','百年老餐厅 Vitti Roma dal 1898 就在附近，开心果Gelato绝了'],
          warnings:['⚠️ 禁止坐在台阶上！违者罚款250-400€！','⚠️ 小心兜售鲜花和手串的人，不要接'],photos:['日落时分从台阶顶端拍摄广场全景','在破船喷泉前拍人像']}},
      {time:'17:45',type:'sight',title:'⛲ 特雷维喷泉（许愿池）',desc:'全球最著名巴洛克喷泉，准备1欧硬币背对许愿！',
        detail:{emoji:'⛲',name:'特雷维喷泉（许愿池）',subtitle:'Fontana di Trevi · 免费 · 24小时',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'30-45分钟'},{label:'最佳时间',value:'21:00后'},{label:'拍照',value:'⭐⭐⭐⭐⭐'}],
          history:{
            summary:'特雷维喷泉是罗马最大的巴洛克喷泉，也是世界上最著名的喷泉之一，建造历时30年。',
            facts:[
              {label:'起源',value:'喷泉源于公元前19年的处女水道桥（Aqua Virgo），传说一位少女指引士兵找到水源'},
              {label:'建造',value:'现在的喷泉由建筑师尼古拉·萨尔维于1732年开始设计建造，1762年完工'},
              {label:'规模',value:'高26.3米、宽49.15米，是罗马最大的喷泉'},
              {label:'雕塑',value:'中央海神尼普顿驾驭两匹海马的马车，象征海洋的平静与汹涌'},
            ],
            description:'许愿池的许愿传统源于18世纪：背对喷泉用右手从左肩抛入一枚硬币可以重返罗马，两枚硬币会找到爱情，三枚硬币则会步入婚姻。每年约有超过100万欧元的硬币被投入喷泉，这些硬币由罗马市政府收集后捐赠给慈善机构。1954年电影《罗马之恋》让许愿传统更加广为人知。'
          },
          highlights:['世界最著名巴洛克喷泉，高26.3米、宽49.15米','背对喷泉右手持硬币从左肩抛入可重返罗马','21:00后人少灯光更梦幻','从北侧小巷拍全景可避开人群'],
          warnings:['白天人非常多，建议晚上再来','准备好1欧硬币','注意防盗！此处小偷高发区'],photos:['北侧小巷拍全景','夜晚灯光下更梦幻']}},
      {time:'18:30',type:'food',title:'🍋 Limon\'è 柠檬冰淇淋',desc:'整颗柠檬挖空填入冰淇淋，拍照超出片！€5-8',
        detail:{emoji:'🍋',name:'Limon\'è',subtitle:'许愿池附近 · €5-8',
          info:[{label:'人均',value:'€5-8'},{label:'类型',value:'冰淇淋'},{label:'位置',value:'许愿池旁'},{label:'推荐',value:'⭐⭐⭐⭐⭐'}],
          highlights:['整颗大柠檬挖空填入冰淇淋/雪葩','拿着到许愿池前拍照出片率极高！','夏天解暑神器，口感清爽不甜腻'],warnings:[],photos:[]}},
      {time:'19:00',type:'food',title:'🍝 Osteria da Fortunata',desc:'Carbonara手工意面，惊艳到灵魂颤抖！€15-25',
        detail:{emoji:'🍝',name:'Osteria da Fortunata',subtitle:'罗马 · €15-25',
          info:[{label:'人均',value:'€15-25'},{label:'类型',value:'手工意面'},{label:'必点',value:'Carbonara'},{label:'推荐',value:'⭐⭐⭐⭐⭐'}],
          highlights:['最正宗的Carbonara手工意面','焦香酥脆猪脸颊肉+浓郁蛋汁+咸香芝士','到店现做，可以看到阿姨在门口擀面'],warnings:['人气很旺，建议早点去或提前预约'],photos:[]}},
      {time:'20:30',type:'sight',title:'🌙 夜游许愿池',desc:'夜晚灯光下更梦幻，人也少很多'},
    ],
    tips:['长途飞行后不要安排太多，轻松漫步为主','西班牙广场附近是购物区，有Gucci、Prada等','🍦 Vitti Roma dal 1898 开心果 Gelato 口味绝了'],
  },
  {
    id:2, date:'5月2日', weekday:'周六', city:'罗马', cityTag:'梵蒂冈',
    title:'圣彼得登顶+万神殿+梵蒂冈博物馆', theme:'上午登顶+城堡→中午万神殿→下午梵蒂冈博物馆16:00场（梵蒂冈博物馆周日闭馆，提前至周六）',
    emoji:'🎨', color:'#7B1FA2',
    bannerGradient:'linear-gradient(135deg,#9C27B0,#6A1B9A)',
    route:['圣彼得大教堂','圣天使城堡','圣天使桥','万神殿','梵蒂冈博物馆','西斯廷小堂'],
    mapCenter:[41.9022,12.4570], mapZoom:14,
    spots:[
      {lat:41.9022,lng:12.4539,name:'圣彼得大教堂',num:'❶'},
      {lat:41.9031,lng:12.4663,name:'圣天使城堡',num:'❷'},
      {lat:41.9013,lng:12.4662,name:'圣天使桥',num:'❸'},
      {lat:41.8986,lng:12.4769,name:'万神殿',num:'❹'},
      {lat:41.9065,lng:12.4536,name:'梵蒂冈博物馆',num:'❺'},
    ],
    timeline:[
      {time:'09:00',type:'sight',title:'⛪ 圣彼得大教堂（含登顶）',desc:'世界第一大教堂！上午第一批登顶人少体验好',badge:'建议预约',
        detail:{emoji:'⛪',name:'圣彼得大教堂',subtitle:'教堂免费 / 穹顶€5-8 · 上午先登顶！',
          info:[{label:'教堂',value:'免费'},{label:'穹顶步行',value:'€5'},{label:'穹顶电梯',value:'€8'},{label:'用时',value:'1.5小时'}],
          history:{
            summary:'圣彼得大教堂（Basilica di San Pietro）是天主教世界最大的教堂，建于耶稣门徒圣伯多禄（圣彼得）的墓地之上。',
            facts:[
              {label:'起源',value:'公元64年使徒圣彼得在此殉道，公元326年君士坦丁大帝在其墓地上建造了第一座教堂'},
              {label:'重建',value:'现教堂1506年开始重建，历时120年，1626年教皇乌尔巴诺八世主持祝圣仪式'},
              {label:'建筑师',value:'先后由布拉曼特、拉斐尔、米开朗基罗等大师主持设计，穹顶由米开朗基罗设计（直径42米）'},
              {label:'规模',value:'教堂长220米、最大宽度150米、穹顶高136米，可容纳6万人'},
              {label:'圣殇',value:'入口右侧的《圣殇》是米开朗基罗24岁时的杰作，也是他唯一署名的作品'},
            ],
            description:'圣彼得大教堂内部珍藏着无数艺术珍品，包括贝尼尼设计的青铜华盖（Baldacchino），高达29米，位于教堂正中祭坛上方。教堂前方的圣彼得广场由贝尼尼设计，284根柱廊形成椭圆形广场，象征教会拥抱世界。2024年12月24日至2026年1月6日期间，教堂的禧年圣门特别开放——这是每25年才开启一次的重要宗教仪式。'
          },
          highlights:['世界第一大教堂，文艺复兴建筑瑰宝','上午第一批登顶人少体验最好！','米开朗基罗《圣殇》在入口右侧（禁闪光灯）','穹顶东侧拍梵蒂冈广场放射状光柱廊','⚠️ 禧年圣门 2024.12.24-2026.1.6 开放！'],
          warnings:['穿长裤/长裙，不能露肩！否则不让进','大背包需寄存（€5），建议轻装','先登顶再逛教堂内部'],
          photos:['📸 穹顶拍梵蒂冈广场光柱廊','📸 殿内拍《圣殇》（禁闪光灯）'],ticketUrl:'https://booking.basilicasanpietro.va/'}},
      {time:'10:30',type:'sight',title:'🏰 圣天使城堡',desc:'步行10分钟即到，上午游客少体验好，€15',
        detail:{emoji:'🏰',name:'圣天使城堡',subtitle:'€15 · 可现场买',
          info:[{label:'门票',value:'€15'},{label:'用时',value:'1小时'},{label:'预约',value:'可现场买'},{label:'推荐',value:'⭐⭐⭐⭐'}],
          history:{
            summary:'圣天使城堡（Castel Sant\'Angelo）历经2000年，从皇帝陵墓到教皇堡垒再到监狱，是罗马历史的缩影。',
            facts:[
              {label:'建造',value:'公元123-139年由哈德良皇帝建造，原为自己和继任者的陵墓（Mausoleum Hadriani）'},
              {label:'命名',value:'公元590年大瘟疫期间，教皇格里高利一世看到天使长米迦勒在城堡顶端收剑入鞘，瘟疫随即终结，遂命名"圣天使城堡"'},
              {label:'用途',value:'先后用作陵墓、军事要塞、教皇避难所、监狱和博物馆'},
              {label:'密道',value:'城堡通过一条长约800米的"Passetto"通道直接连接梵蒂冈，是教皇的紧急逃生通道'},
            ],
            description:'城堡共5层，从底部的陵墓层到顶部的天使铜像露台，每一层都记录着不同时代的历史。文艺复兴时期曾关押过包括切利尼和布鲁诺在内的著名囚犯。丹·布朗的小说《天使与魔鬼》中，圣天使城堡是光照派的重要据点。顶层的天使铜像和360度露台提供了台伯河和罗马城的壮丽景色。'
          },
          highlights:['最初是哈德良皇帝陵墓，后成为教皇城堡和监狱','顶层天使铜像可360°俯瞰台伯河和罗马城','电影《天使与魔鬼》重要取景地'],
          warnings:['上午参观人少体验好'],photos:['📸 顶层俯瞰台伯河','📸 城堡与圣天使桥合影']}},
      {time:'11:30',type:'sight',title:'🌉 圣天使桥',desc:'罗马最美桥梁！12座天使雕像'},
      {time:'12:00',type:'food',title:'🍕 Mariuccia 披萨店（午餐）',desc:'攻略评价Top1！就在万神殿旁边，四人才70欧',
        detail:{emoji:'🍕',name:'Mariuccia 披萨店',subtitle:'万神殿附近 · €10-20',
          info:[{label:'人均',value:'€10-20'},{label:'评价',value:'⭐ TOP 1'},{label:'位置',value:'P.za della Cancelleria 92'},{label:'预约',value:'只能walk in'}],
          highlights:['攻略评价最高！"人生中最好吃的披萨"','4个人才吃了70欧，性价比极高','本地经典披萨+开心果火腿披萨必点','就在万神殿旁边步行3分钟'],
          warnings:['只能walk in不接受预约','中午高峰需要等位'],photos:[]}},
      {time:'13:00',type:'food',title:'☕ 金杯咖啡',desc:'万神殿附近百年咖啡店，咖啡沙冰+罗马奶油包'},
      {time:'13:30',type:'sight',title:'🏛️ 万神殿 Pantheon',desc:'2000年建筑奇迹！世界最大无钢筋穹顶，€5（已预约13:30）',badge:'需预约',
        detail:{emoji:'🏛️',name:'万神殿 Pantheon',subtitle:'€5 · 已预约13:30',
          info:[{label:'门票',value:'€5'},{label:'用时',value:'45分钟'},{label:'预约',value:'🔴 已预约13:30'},{label:'亮点',value:'天眼光柱'}],
          history:{
            summary:'万神殿（Pantheon）是古罗马保存最完好的建筑，拥有2000年历史，其穹顶至今仍是世界最大的无钢筋混凝土穹顶。',
            facts:[
              {label:'初建',value:'公元前27年由罗马将军阿格里帕始建，献给所有神明（Pan=所有，Theon=神）'},
              {label:'重建',value:'公元118-128年由哈德良皇帝重建为现今形态'},
              {label:'穹顶',value:'穹顶直径43.3米，顶部"天眼"直径9米，是唯一光源，2000年来未使用任何钢筋'},
              {label:'转变',value:'公元609年被改为天主教堂（圣母与诸殉道者教堂），因此得以完好保存'},
              {label:'墓碑',value:'文艺复兴三杰之一的拉斐尔（1483-1520）葬于此，还有意大利两位国王的陵墓'},
            ],
            description:'万神殿的穹顶是古罗马建筑工程的巅峰杰作。穹顶使用了混凝土浇筑技术，从底部到顶部混凝土中的骨料逐渐变轻（从沉重的凝灰岩到轻质的浮石），体现了古罗马工程师的智慧。穹顶顶部的圆洞（Oculus）不仅是唯一光源，也是调节室内温度的通风口。下雨时雨水会从天眼落入，通过地面的排水系统排出。米开朗基罗称其为"天使的设计"。'
          },
          highlights:['世界上最大无钢筋混凝土穹顶，2000年前的建筑奇迹','穹顶正中圆洞（天眼）直径9米是唯一光源','内部有拉斐尔墓碑'],
          warnings:['🔴 务必提前预约！现场排队半小时以上','现场购票：最左侧现金，第二排预约通道，最右信用卡'],photos:['📸 殿内中央仰拍穹顶与光柱','📸 找到拉斐尔墓碑'],
          ticketUrl:'https://portale.museiitaliani.it/b2c/'}},
      {time:'14:15',type:'default',title:'🚶 自由逛吃/休息',desc:'万神殿周边逛逛，补充体力为下午博物馆做准备'},
      {time:'15:30',type:'transport',title:'🚌 前往梵蒂冈博物馆',desc:'打车/公交约20分钟'},
      {time:'16:00',type:'sight',title:'🎨 梵蒂冈博物馆+西斯廷小堂',desc:'已预约16:00入场！精华路线2小时：拉奥孔→拉斐尔画室→西斯廷小堂',badge:'已预约16:00',
        detail:{emoji:'🎨',name:'梵蒂冈博物馆',subtitle:'在线€25 · 已预约16:00入场',
          info:[{label:'门票',value:'在线€25'},{label:'用时',value:'约2小时'},{label:'预约',value:'🟢 已预约16:00'},{label:'重点',value:'西斯廷小堂'}],
          history:{
            summary:'梵蒂冈博物馆是世界上最重要的艺术博物馆之一，收藏了跨越数千年的艺术珍品，其中的西斯廷小堂是文艺复兴艺术的巅峰。',
            facts:[
              {label:'创建',value:'1506年教皇朱利叶斯二世创建，最初仅是教皇的私人收藏'},
              {label:'规模',value:'拥有54个展厅、约7万件展品（仅展出约2万件），总面积超过7万平方米'},
              {label:'西斯廷小堂',value:'米开朗基罗1508-1512年独自完成天顶画《创世纪》，1536-1541年完成祭坛画《最后的审判》'},
              {label:'拉斐尔画室',value:'拉斐尔1509-1511年绘制的《雅典学院》被誉为文艺复兴最伟大的壁画之一'},
              {label:'拉奥孔',value:'1506年出土的古希腊雕塑《拉奥孔群像》是博物馆最早的重要收藏之一'},
            ],
            description:'西斯廷小堂原是教皇的私人礼拜堂，同时也是新教皇选举（密议会）的举行地。米开朗基罗起初不愿接受天顶画的委托（他自认是雕塑家而非画家），但最终花了4年时间创作了包含300多个人物的《创世纪》天顶画，被誉为西方艺术史上最伟大的成就之一。其中"创造亚当"一幕——上帝之手即将触碰亚当——已成为最广为人知的艺术图像之一。'
          },
          highlights:['世界上最重要的艺术博物馆之一','⏰ 16:00入场精华路线：拉奥孔→八角庭院→拉斐尔画室《雅典学院》→西斯廷小堂','西斯廷小堂：米开朗基罗《创世纪》天顶画+《最后的审判》','下午场人流较少，参观体验更好','闭馆20:00，参观时间约2小时足够精华路线'],
          warnings:['🟢 已预约16:00入场','⚠️ 西斯廷小堂严禁拍照！罚款200-500€！','到了梵蒂冈信号不好，提前截图保存门票','精简路线优先看三大必看：拉奥孔、拉斐尔画室、西斯廷小堂'],
          photos:['📸 拉斐尔画室可以拍照','📸 博物馆中庭可拍穹顶'],ticketUrl:'https://tickets.museivaticani.va/home'}},
      {time:'18:30',type:'transport',title:'🚶 步行前往晚餐',desc:'从梵蒂冈博物馆前往餐厅约20分钟'},
      {time:'19:00',type:'food',title:'🥩 Saltimbocca ristorante（晚餐）',desc:'攻略评价Top2！炖牛尾超美味，鸡尾酒丰富',
        detail:{emoji:'🥩',name:'Saltimbocca ristorante',subtitle:'罗马 · 需预约',
          info:[{label:'评价',value:'⭐ TOP 2'},{label:'必点',value:'炖牛尾'},{label:'预约',value:'建议预约'},{label:'鸡尾酒',value:'很丰富'}],
          highlights:['攻略评价Top2','炖牛尾超级美味！','鸡尾酒单丰富随便点都好喝'],warnings:['建议提前预约'],photos:[]}},
    ],
    tips:['梵蒂冈博物馆已预约16:00入场，精简路线优先看：拉奥孔→拉斐尔画室→西斯廷小堂','上午先登顶圣彼得+圣天使城堡（体力活）→下午博物馆（脑力活），体力分配更科学','万神殿13:30预约不变，提前到Mariuccia吃午餐+金杯咖啡','到了梵蒂冈信号不好，提前截图保存门票','穿长裤/长裙，不能露肩！'],
  },
  {
    id:3, date:'5月3日', weekday:'周日', city:'罗马→佛罗伦萨', cityTag:'古迹线',
    title:'古迹Citywalk+赴佛罗伦萨', theme:'斗兽场→凯旋门→帕拉丁山→真理之口→威尼斯广场，傍晚赴佛罗伦萨',
    emoji:'🏟️', color:'#E65100',
    bannerGradient:'linear-gradient(135deg,#FF8A65,#D84315)',
    route:['斗兽场','凯旋门','帕拉丁山','古罗马广场','真理之口','纳沃纳广场','圣依纳爵堂','威尼斯广场','Roma Termini','佛罗伦萨'],
    mapCenter:[41.8930,12.4880], mapZoom:14,
    spots:[
      {lat:41.8902,lng:12.4922,name:'斗兽场',num:'❶'},
      {lat:41.8898,lng:12.4905,name:'凯旋门',num:'❷'},
      {lat:41.8893,lng:12.4867,name:'帕拉丁山',num:'❸'},
      {lat:41.8925,lng:12.4853,name:'古罗马广场',num:'❹'},
      {lat:41.8882,lng:12.4815,name:'真理之口',num:'❺'},
      {lat:41.8992,lng:12.4731,name:'纳沃纳广场',num:'❻'},
      {lat:41.8988,lng:12.4797,name:'圣依纳爵堂',num:'❼'},
      {lat:41.8957,lng:12.4823,name:'威尼斯广场',num:'❽'},
    ],
    timeline:[
      {time:'08:30',type:'sight',title:'🏟️ 罗马斗兽场 Colosseum',desc:'古罗马帝国象征！联票€24含地下层+竞技场',badge:'需预约',
        detail:{emoji:'🏟️',name:'罗马斗兽场',subtitle:'Colosseo · 联票€24 · 需提前预约',
          info:[{label:'门票',value:'联票€24'},{label:'用时',value:'2-2.5小时'},{label:'开放',value:'08:30-日落前1h'},{label:'预约',value:'🔴 必须预约'}],
          history:{
            summary:'古罗马斗兽场（Colosseum）是古罗马帝国最伟大的建筑之一，也是世界上现存最大的古罗马圆形竞技场。',
            facts:[
              {label:'建造时期',value:'公元72-80年，由弗拉维王朝皇帝韦斯帕先下令建造，其子提图斯主持完工'},
              {label:'规模',value:'椭圆形建筑，长188米、宽156米、高48.5米，可容纳5万-8万名观众'},
              {label:'用途',value:'举办角斗士格斗、野兽狩猎表演、模拟海战及公开处刑，持续使用近500年'},
              {label:'建筑特色',value:'四层拱券结构，依次采用多利克柱式、爱奥尼亚柱式和科林斯柱式'},
              {label:'地下结构',value:'地下两层密道系统（hypogeum）用于关押角斗士和猛兽，通过升降机送入竞技场'},
            ],
            description:'斗兽场原名弗拉维圆形竞技场，建在尼禄皇帝黄金宫殿人工湖旧址上。2007年入选新世界七大奇迹，每年吸引超过600万游客。'
          },
          highlights:['古罗马帝国象征，建于公元70-80年，可容纳5万人','联票包含：斗兽场1/2层+竞技场+地下层+帕拉丁山+古罗马广场','地下层可看角斗士通道，非常震撼'],
          warnings:['🔴 务必提前2-4周在官网预约！五一期间非常紧张','如抢不到英文讲解，可试意大利语场次','强烈建议早上第一批进入'],
          photos:['📸 早场空旷时拍内部拱券','📸 后面天桥上拍全景','📸 侧面残缺处坐台阶拍人像'],
          ticketUrl:'https://ticketing.colosseo.it/en/'}},
      {time:'11:00',type:'sight',title:'🏛️ 君士坦丁凯旋门',desc:'与斗兽场相邻，拱门内拍斗兽场全景'},
      {time:'11:15',type:'sight',title:'⛰️ 帕拉丁山+古罗马广场',desc:'含在斗兽场联票内，租中文讲解器€8/台',
        detail:{emoji:'⛰️',name:'帕拉丁山+古罗马广场',subtitle:'含在联票内',
          info:[{label:'门票',value:'联票包含'},{label:'用时',value:'1-1.5小时'},{label:'讲解器',value:'€8/台'},{label:'推荐',value:'⭐⭐⭐⭐'}],
          history:{
            summary:'帕拉丁山是罗马七丘之一，传说罗马城的建立者罗慕路斯和雷穆斯在此被母狼哺育，是罗马文明的发源地。',
            facts:[
              {label:'起源',value:'根据传说，公元前753年罗慕路斯在帕拉丁山上建立了罗马城'},
              {label:'皇宫区',value:'共和国末期至帝国时期，这里成为罗马皇帝的宫殿所在地'},
              {label:'古罗马广场',value:'山脚下的Forum Romanum是古罗马政治、宗教和商业中心'},
              {label:'遗迹',value:'现存遗迹包括奥古斯都宫、提比略宫、元老院、凯撒神庙等'},
            ],
            description:'英语中"宫殿"（Palace）一词就来源于帕拉丁山（Palatine）。从帕拉丁山顶可以俯瞰整个古罗马广场的废墟群。'
          },
          highlights:['罗马帝国皇帝的宫殿遗址','帕拉丁山顶平台俯瞰整片废墟','重点看元老院遗址、凯撒神庙'],
          warnings:['时限内只能进入1次','注意防晒补水'],photos:['📸 帕拉丁山顶平台俯瞰废墟']}},
      {time:'12:30',type:'transport',title:'🚶 步行前往真理之口',desc:'约8分钟步行'},
      {time:'13:00',type:'sight',title:'👄 真理之口',desc:'罗马假日经典拍照点！9:30-17:50',
        detail:{emoji:'👄',name:'真理之口',subtitle:'Bocca della Verità · 免费',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'20-30分钟'},{label:'开放',value:'9:30-17:50'},{label:'排队',value:'约15-30分钟'}],
          history:{
            summary:'真理之口（Bocca della Verità）是一块直径1.75米的大理石圆盘，可能是古罗马时代的排水井盖。',
            facts:[
              {label:'年代',value:'推测为公元1世纪的古罗马石刻作品'},
              {label:'位置',value:'位于科斯梅丁圣母教堂门廊中'},
              {label:'传说',value:'中世纪传说：将手伸入石嘴中，如果说谎手就会被咬断'},
              {label:'电影',value:'1953年《罗马假日》中经典场景使其世界闻名'},
            ],
            description:'真理之口的确切用途至今仍有争议，因"说谎者断手"的传说而成为著名景点。'
          },
          highlights:['《罗马假日》最经典场景','传说说谎者手会被咬住','位于科斯梅丁圣母教堂门廊'],
          warnings:['需排队等候拍照约15-30分钟','17:50关门注意时间'],photos:['📸 手伸入石嘴做害怕表情']}},
      {time:'13:30',type:'food',title:'🍝 午餐',desc:'真理之口附近当地餐厅或Trastevere区域，人均€15-25'},
      {time:'14:30',type:'sight',title:'⛲ 纳沃纳广场',desc:'四河喷泉所在地，罗马最美巴洛克广场',
        detail:{emoji:'⛲',name:'纳沃纳广场',subtitle:'Piazza Navona · 免费',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'30分钟'},{label:'特色',value:'四河喷泉'},{label:'氛围',value:'⭐⭐⭐⭐⭐'}],
          history:{
            summary:'纳沃纳广场建于公元1世纪图密善皇帝的竞技场遗址之上，是罗马最美的巴洛克广场。',
            facts:[
              {label:'起源',value:'广场保留了公元86年图密善竞技场的椭圆形轮廓'},
              {label:'四河喷泉',value:'贝尼尼1651年创作，四座雕像代表尼罗河、恒河、多瑙河和拉普拉塔河'},
              {label:'建筑',value:'广场西侧的圣阿涅塞教堂由博罗米尼设计'},
              {label:'传统',value:'历史上广场曾在夏天被注水成为"湖泊"供贵族划船'},
            ],
            description:'纳沃纳广场是罗马巴洛克艺术的瑰宝。每年圣诞节期间广场举办著名的圣诞市集。'
          },
          highlights:['罗马最美巴洛克广场之一','贝尼尼《四河喷泉》代表四大河流','露天咖啡馆可享受罗马午后'],
          warnings:['广场餐厅价格偏贵，喝咖啡即可'],photos:['📸 广场北侧拍四河喷泉全景']}},
      {time:'15:00',type:'sight',title:'⛪ 圣依纳爵堂',desc:'免费小镜子看3D天顶画透视效果！',
        detail:{emoji:'⛪',name:'圣依纳爵堂',subtitle:'免费（镜子€1）',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'30分钟'},{label:'亮点',value:'3D天顶画'},{label:'推荐',value:'⭐⭐⭐⭐⭐'}],
          history:{
            summary:'圣依纳爵堂以其令人惊叹的"假穹顶"天顶画闻名于世。',
            facts:[
              {label:'建造',value:'1626-1650年建造，献给耶稣会创始人圣依纳爵·罗耀拉'},
              {label:'天顶画',value:'安德烈·波佐1685年创作的《圣依纳爵的荣耀》，用透视法画出3D穹顶效果'},
              {label:'假穹顶',value:'因资金不足无法建真穹顶，用绘画创造了完美的视觉幻觉'},
              {label:'技巧',value:'站在教堂中央黄色标记处观看效果最佳'},
            ],
            description:'安德烈·波佐运用最先进的建筑透视学原理，在完全平坦的天花板上绘制出壮丽的巴洛克穹顶，被称为"视觉欺骗的杰作"。'
          },
          highlights:['入口借免费小镜子看天顶画透视效果！','天顶画用平面画出了3D穹顶效果','比西斯廷小堂人少但震撼程度不相上下'],
          warnings:['避免直接仰头拍会变形，用镜子反射效果最佳'],photos:['📸 教堂中央用镜子反射拍天顶画']}},
      {time:'15:30',type:'sight',title:'🏛️ 威尼斯广场',desc:'罗马最大广场！白色大理石"打字机"建筑'},
      {time:'16:30',type:'transport',title:'🚶 前往Roma Termini',desc:'步行约15分钟到火车站'},
      {time:'17:30',type:'transport',title:'🚄 高铁前往佛罗伦萨',desc:'€15-50，约1.5小时到达Firenze SMN',
        detail:{emoji:'🚄',name:'罗马→佛罗伦萨高铁',subtitle:'Roma Termini → Firenze SMN',
          info:[{label:'票价',value:'€15-50'},{label:'用时',value:'约1.5小时'},{label:'公司',value:'Trenitalia/Italo'},{label:'购票',value:'携程/官网'}],
          highlights:['Trenitalia Frecciarossa 或 Italo 高铁','提前购买更便宜','携程直接购买支付宝支付','不用安检进站出站不用验票'],
          warnings:['⚠️ 火车开车前3分钟都可能更换站台！','多关注站台大屏，随时准备奔跑','候车站台显示可能不准'],photos:[]}},
      {time:'19:30',type:'food',title:'🍕 Giotto Pizzeria（晚餐）',desc:'小红书推荐佛罗伦萨人生披萨！本地人推荐',
        detail:{emoji:'🍕',name:'Giotto Pizzeria Firenze',subtitle:'佛罗伦萨 · 本地人推荐',
          info:[{label:'类型',value:'披萨'},{label:'必点',value:'米其林合作款'},{label:'推荐',value:'⭐⭐⭐⭐⭐'}],
          highlights:['小红书很多人推荐的"人生披萨"','本地人推荐，不是纯网红店','点米其林合作款 bistecca 披萨！'],warnings:[],photos:[]}},
    ],
    tips:['斗兽场一定要提前2-4周在官网预约联票！','联票含斗兽场+帕拉丁山+古罗马广场，一次逛完','圣依纳爵堂入口借免费小镜子看天顶画效果更佳','真理之口17:50关门注意时间安排','⚠️ 火车站台可能临时变更，注意大屏幕'],
  },
  {
    id:4, date:'5月4日', weekday:'周一', city:'佛罗伦萨→比萨', cityTag:'比萨/佛罗伦萨',
    title:'比萨半日游+佛罗伦萨漫步', theme:'上午比萨斜塔打卡，下午佛罗伦萨自由逛+日落（周一博物馆闭馆）',
    emoji:'🗼', color:'#4CAF50',
    bannerGradient:'linear-gradient(135deg,#66BB6A,#2E7D32)',
    route:['火车赴比萨','奇迹广场','比萨斜塔','返回佛罗伦萨','老桥·HUMILIS','米开朗基罗广场'],
    mapCenter:[43.7230,10.3966], mapZoom:11,
    spots:[
      {lat:43.7230,lng:10.3966,name:'比萨斜塔',num:'❶'},
      {lat:43.7680,lng:11.2531,name:'老桥',num:'❷'},
      {lat:43.7629,lng:11.2650,name:'米开朗基罗广场',num:'❸'},
    ],
    timeline:[
      {time:'08:00',type:'transport',title:'🚂 火车赴比萨',desc:'约50-70分钟，€9-15区域列车'},
      {time:'09:20',type:'sight',title:'🗼 奇迹广场+比萨斜塔',desc:'UNESCO世界遗产，斜塔可攀登至顶',badge:'需预约',
        detail:{emoji:'🗼',name:'比萨斜塔+奇迹广场',subtitle:'UNESCO世界遗产 · 斜塔需预约',
          info:[{label:'斜塔',value:'需预约'},{label:'用时',value:'2-2.5小时'},{label:'到达',value:'步行20分钟'},{label:'预约',value:'🔴 易售罄'}],
          history:{
            summary:'比萨斜塔（Torre Pendente di Pisa）是比萨大教堂的独立钟楼，因地基不均匀沉降而倾斜，成为世界上最著名的建筑"意外"。',
            facts:[
              {label:'建造',value:'1173年开始建造，因倾斜和战争等原因断断续续，历时177年，1350年才完工'},
              {label:'建筑师',value:'第一阶段建筑师可能是博纳诺·皮萨诺（Bonanno Pisano），建到第3层时已开始倾斜'},
              {label:'倾斜',value:'最大倾斜角度曾达5.5度（约5.5米偏移），1990-2001年修复后稳定在约3.97度'},
              {label:'规模',value:'圆形8层建筑，高约56米（低侧），共有294级台阶通往顶部'},
              {label:'伽利略',value:'传说1589年伽利略曾在塔顶进行自由落体实验，证明不同重量的物体同时落地（可能是后人杜撰）'},
            ],
            description:'奇迹广场（Piazza dei Miracoli）是联合国教科文组织世界文化遗产，除了斜塔外还包括比萨大教堂（Duomo di Pisa，始建于1063年）、洗礼堂和墓园。整个广场的建筑群被视为中世纪罗马式建筑的典范。斜塔的倾斜原因是东南侧的地基由松软的粘土和沙子构成，1990-2001年的修复工程通过移除北侧地基下方的土壤成功地将倾斜角度减小了约44厘米，确保了斜塔至少在未来200年内的安全。'
          },
          highlights:['UNESCO世界文化遗产','比萨斜塔可攀登至顶部俯瞰全城','奇迹广场还有比萨大教堂和洗礼堂','从火车站步行约20分钟沿途经过阿诺河'],
          warnings:['⚠️ 斜塔旺季经常售罄按时段限量','建议提前在线预约'],photos:['📸 经典"扶塔"姿势','📸 广场全景']}},
      {time:'11:30',type:'food',title:'🍝 比萨午餐',desc:'历史中心找托斯卡纳小餐馆'},
      {time:'13:30',type:'transport',title:'🚂 返回佛罗伦萨',desc:'约50-70分钟，€9-15'},
      {time:'15:00',type:'food',title:'🥪 All\'Antico Vinaio',desc:'传奇帕尼尼！面包皮嘎嘣脆火腿芝士完美',
        detail:{emoji:'🥪',name:'All\'Antico Vinaio',subtitle:'€5-8 · 传奇帕尼尼',
          info:[{label:'人均',value:'€5-8'},{label:'评价',value:'传奇级！'},{label:'推荐',value:'paradise!'},{label:'备选',value:'火车站分店'}],
          highlights:['佛罗伦萨传奇帕尼尼！排队人潮说明一切','面包皮烤得嘎嘣脆，火腿芝士比例完美','推荐：paradise!（开心果酱肉肠）inferno（烤猪肉辣椒）','⚠️ 火车站也有分店不排队可打包带火车！'],
          warnings:['排队可能较长耐心等待'],photos:[]}},
      {time:'16:00',type:'shopping',title:'🛍️ 佛罗伦萨自由逛街/购物',desc:'佛罗伦萨皮具闻名！圣洛伦佐皮具市场、SMN药妆店等（周一博物馆闭馆，正好逛街购物）'},
      {time:'17:30',type:'shopping',title:'🌉 老桥+HUMILIS首饰店 🛍️',desc:'佛罗伦萨最著名的桥！HUMILIS买鸢尾花戒指',
        detail:{emoji:'🌉',name:'老桥 + HUMILIS',subtitle:'Ponte Vecchio · 免费',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'1小时'},{label:'购物',value:'HUMILIS首饰'},{label:'特色',value:'桥上珠宝店'}],
          history:{
            summary:'老桥（Ponte Vecchio）建于1345年，是佛罗伦萨最古老的桥梁，也是欧洲最著名的中世纪石拱桥之一。',
            facts:[
              {label:'建造',value:'现存的桥建于1345年，替代了之前被洪水冲毁的罗马时代木桥'},
              {label:'瓦萨里走廊',value:'1565年美第奇家族在桥上方建造了瓦萨里走廊（Corridoio Vasariano），连接旧宫与彼蒂宫'},
              {label:'珠宝店',value:'1593年费尔迪南多一世下令将桥上的屠夫和皮匠铺换成金银珠宝店，延续至今'},
              {label:'二战',value:'1944年德军撤退时炸毁了佛罗伦萨所有桥梁，唯独留下了老桥（传说是希特勒下令保护）'},
            ],
            description:'老桥横跨阿诺河最窄处，三个桥拱的设计在当时是创新之举。桥中段两侧有开放的空间，可以欣赏阿诺河两岸的风景。瓦萨里走廊曾用于让美第奇大公在不经过公共街道的情况下往返于两座宫殿之间。走廊内还收藏了大量自画像。如今桥上约有30家珠宝店和金店，是世界上最独特的购物场所之一。'
          },
          highlights:['佛罗伦萨最著名的桥！桥上全是金银珠宝店','HUMILIS Made in Assisi 就在老桥上','阿西西手工珠宝，可买鸢尾花（iris）戒指等','佛罗伦萨/罗马/威尼斯都有分店'],
          warnings:['桥上人很多，注意随身物品'],photos:['📸 在桥上拍阿诺河两岸','📸 从河岸远拍老桥全景']}},
      {time:'19:00',type:'sight',title:'🌅 米开朗基罗广场（日落）',desc:'俯瞰整个佛罗伦萨全城+阿诺河+穹顶！5月日落约20:20',
        detail:{emoji:'🌅',name:'米开朗基罗广场',subtitle:'免费 · 日落最佳观赏点',
          info:[{label:'门票',value:'免费'},{label:'最佳',value:'19:30-20:20'},{label:'推荐',value:'⭐⭐⭐⭐⭐'},{label:'到达',value:'步行/公交'}],
          history:{
            summary:'米开朗基罗广场（Piazzale Michelangelo）建于1869年，是为纪念文艺复兴巨匠米开朗基罗而建的城市观景台。',
            facts:[
              {label:'建造',value:'1869年由建筑师朱塞佩·波吉设计，作为佛罗伦萨城市改造计划的一部分'},
              {label:'大卫像',value:'广场中央有米开朗基罗《大卫》的青铜复制品，以及美第奇小堂四座寓言雕塑的复制品'},
              {label:'位置',value:'位于阿诺河南岸的山丘上，海拔约104米，是俯瞰佛罗伦萨全景的最佳位置'},
              {label:'视野',value:'可以同时看到圣母百花穹顶、旧宫钟楼、老桥和阿诺河的壮丽全景'},
            ],
            description:'米开朗基罗广场原本设计为一座完整的米开朗基罗博物馆（现为餐厅），用以陈列大师的雕塑作品。广场是每位到访佛罗伦萨游客的必到之处，尤其是日落时分，金色阳光洒在红色屋顶和穹顶上的景象令人终生难忘。从老桥步行上山约25-30分钟，也可以乘坐12路或13路公交车到达。5月初日落约在20:20左右，建议19:30前到场占据有利位置。'
          },
          highlights:['日落最佳观赏点！','俯瞰整个佛罗伦萨全城+阿诺河+圣母百花穹顶','广场上有大卫像复制品','5月初日落约20:20，建议19:30到场'],
          warnings:['从老桥步行约25-30分钟上山','提前到占好位置看日落'],photos:['📸 日落时拍佛罗伦萨天际线']}},
      {time:'20:30',type:'food',title:'🍝 i\'Capaccino（晚餐）',desc:'圣母百花附近，不是网红店但很好吃'},
    ],
    tips:['比萨半日游足够上午去下午回','建议尽早出发避开旅行团','周一乌菲兹和学院美术馆均闭馆，正好安排比萨+购物','5月日落约20:20，米开朗基罗广场建议19:30到场','🍦 回佛罗伦萨后路过Venchi一定进！找有巧克力墙那家'],
  },
  {
    id:5, date:'5月5日', weekday:'周二', city:'佛罗伦萨', cityTag:'佛罗伦萨',
    title:'佛罗伦萨Citywalk+双馆日', theme:'文艺复兴之都漫步，学院美术馆+乌菲兹+穹顶（周二博物馆全开）',
    emoji:'🌸', color:'#2E86AB',
    bannerGradient:'linear-gradient(135deg,#42A5F5,#1565C0)',
    route:['中央市场','圣母百花大教堂','学院美术馆','领主广场','乌菲兹美术馆','老桥','晚餐'],
    mapCenter:[43.7710,11.2555], mapZoom:14,
    spots:[
      {lat:43.7764,lng:11.2534,name:'中央市场',num:'❶'},
      {lat:43.7731,lng:11.2560,name:'圣母百花大教堂',num:'❷'},
      {lat:43.7764,lng:11.2534,name:'学院美术馆',num:'❸'},
      {lat:43.7694,lng:11.2553,name:'领主广场',num:'❹'},
      {lat:43.7678,lng:11.2556,name:'乌菲兹美术馆',num:'❺'},
      {lat:43.7680,lng:11.2531,name:'老桥',num:'❻'},
    ],
    timeline:[
      {time:'08:30',type:'food',title:'🥩 中央市场吃早餐',desc:'必吃牛肚包 da nerbone！佛罗伦萨特色',
        detail:{emoji:'🥩',name:'中央市场·牛肚包',subtitle:'8:30-15:00',
          info:[{label:'营业',value:'8:30-15:00'},{label:'必吃',value:'牛肚包'},{label:'摊位',value:'da nerbone'},{label:'备选',value:'bambi'}],
          highlights:['佛罗伦萨中央市场，当地人的美食天堂','必吃牛肚包 da nerbone','二楼美食广场一楼传统市场'],warnings:['注意营业时间8:30-15:00下午关'],photos:[]}},
      {time:'09:00',type:'food',title:'☕ Caffè Gilli 百年咖啡店',desc:'奶油包好吃不腻'},
      {time:'09:30',type:'sight',title:'⛪ 圣母百花大教堂',desc:'佛罗伦萨地标！布鲁内列斯基穹顶是建筑奇迹',badge:'穹顶需预约',
        detail:{emoji:'⛪',name:'圣母百花大教堂',subtitle:'教堂免费 / 穹顶需预约',
          info:[{label:'教堂',value:'免费'},{label:'穹顶',value:'需预约'},{label:'用时',value:'1-1.5小时'},{label:'预约',value:'🔴 需提前'}],
          history:{
            summary:'圣母百花大教堂（Cattedrale di Santa Maria del Fiore）是佛罗伦萨的标志性建筑，其穹顶是文艺复兴建筑工程的最伟大成就。',
            facts:[
              {label:'始建',value:'1296年由建筑师阿诺尔福·迪·坎比奥开始建造，教堂主体1436年完工'},
              {label:'穹顶',value:'菲利波·布鲁内列斯基1420-1436年设计建造，不使用脚手架和飞扶壁，直径45.5米'},
              {label:'钟楼',value:'乔托钟楼由乔托于1334年开始设计，高84.7米，可攀登414级台阶'},
              {label:'洗礼堂',value:'对面的圣乔瓦尼洗礼堂拥有吉贝尔蒂设计的"天堂之门"青铜浮雕（米开朗基罗命名）'},
              {label:'外观',value:'外墙采用白色卡拉拉大理石、粉色大理石和绿色普拉托大理石三色镶嵌'},
            ],
            description:'布鲁内列斯基的穹顶是工程史上的奇迹——在没有现代技术的15世纪，他发明了独特的双壳结构和鱼骨砌法，在内外两层穹壳之间创造了可攀登的空间。穹顶内部有瓦萨里和祖卡里创作的巨幅壁画《最后的审判》，面积达3600平方米，是当时世界上最大的壁画。穹顶的建造方法至今仍有未完全解明的技术细节，体现了文艺复兴时期佛罗伦萨的创新精神。'
          },
          highlights:['佛罗伦萨最著名地标','布鲁内列斯基穹顶是建筑史奇迹','穹顶内有瓦萨里《最后的审判》','外部粉绿白大理石贴面非常漂亮','旁边乔托钟楼可攀登414级台阶'],
          warnings:['教堂免费但穹顶需购票预约','登穹顶需爬463级台阶无电梯！'],photos:['📸 教堂正面拍全景','📸 穹顶内仰拍壁画'],ticketUrl:'https://tickets.duomo.firenze.it'}},
      {time:'10:30',type:'sight',title:'🎨 学院美术馆',desc:'米开朗基罗《大卫》真迹！必看！',badge:'需预约',
        detail:{emoji:'🗿',name:'学院美术馆',subtitle:'Galleria dell\'Accademia · 需预约',
          info:[{label:'门票',value:'€12-16'},{label:'用时',value:'1-1.5小时'},{label:'预约',value:'🔴 需预约'},{label:'重点',value:'大卫真迹'}],
          history:{
            summary:'学院美术馆（Galleria dell\'Accademia）因收藏米开朗基罗的《大卫》真迹而闻名于世，是佛罗伦萨访问量第二大的博物馆。',
            facts:[
              {label:'创建',value:'1784年佛罗伦萨大公利奥波德创建，最初是佛罗伦萨美术学院的教学收藏'},
              {label:'大卫像',value:'1873年米开朗基罗的《大卫》从领主广场移至此处保护，至今已150多年'},
              {label:'大卫',value:'米开朗基罗1501-1504年用一整块卡拉拉大理石雕刻，高5.17米（含底座6.34米），仅26岁'},
              {label:'囚徒系列',value:'馆内还展示了米开朗基罗未完成的4座"囚徒"（Prigioni）雕塑，可以看到他的创作过程'},
              {label:'圣马太',value:'未完成的《圣马太》雕塑也是重要展品，展现了米开朗基罗"从石头中解放灵魂"的创作理念'},
            ],
            description:'米开朗基罗年仅26岁时接受委托，用一块被其他雕塑家弃用的巨型大理石雕刻了《大卫》。这座雕像描绘了大卫与巨人歌利亚战斗前的瞬间——专注、紧张而自信的眼神。原本计划放在圣母百花大教堂顶部，但完工后效果太过震撼，最终被安放在领主广场入口。走廊两侧的"囚徒"雕塑保留了从粗石中"解放"人体的中间状态，是理解米开朗基罗雕塑哲学的珍贵资料。'
          },
          highlights:['米开朗基罗《大卫》真迹！必看！','高5.17米的大理石雕像令人震撼','博物馆还有米开朗基罗未完成的"囚徒"系列'],
          warnings:['🔴 需提前2-4周在官网预约'],photos:['📸 仰拍大卫像展现其雄伟'],ticketUrl:'https://www.galleriaaccademiafirenze.it'}},
      {time:'12:00',type:'food',title:'🍝 trattoria ZaZa（午餐）',desc:'必点 Beef Fillet、龙虾意面、布丁',
        detail:{emoji:'🍝',name:'trattoria ZaZa',subtitle:'建议提前预定',
          info:[{label:'必点',value:'Beef Fillet'},{label:'预约',value:'官网预定'},{label:'备选',value:'11点walk in'},{label:'推荐',value:'⭐⭐⭐⭐⭐'}],
          highlights:['必点：Zà Zà style Beef Fillet（适合2人牛排）','龙虾意面招牌','布丁甜品好吃'],warnings:['中午高峰排队较长'],photos:[]}},
      {time:'13:30',type:'sight',title:'🎨 乌菲兹美术馆',desc:'波提切利《维纳斯的诞生》达芬奇、拉斐尔、卡拉瓦乔（已预约13:30）',badge:'已预约13:30',
        detail:{emoji:'🎨',name:'乌菲兹美术馆',subtitle:'€20-25 · 已预约13:30',
          info:[{label:'门票',value:'€20-25'},{label:'用时',value:'3-3.5小时'},{label:'预约',value:'🟢 已预约13:30'},{label:'重点',value:'维纳斯的诞生'}],
          history:{
            summary:'乌菲兹美术馆（Galleria degli Uffizi）是世界上最古老、最重要的美术馆之一，收藏了从13世纪到18世纪的意大利和欧洲艺术精品。',
            facts:[
              {label:'建造',value:'1560年由瓦萨里为美第奇家族科西莫一世设计建造，原为佛罗伦萨行政办公楼（Uffizi=办公室）'},
              {label:'开馆',value:'1765年正式对公众开放，是世界上最早的公共美术馆之一'},
              {label:'馆藏',value:'收藏约10万件作品，包括波提切利、达芬奇、拉斐尔、米开朗基罗、卡拉瓦乔等大师杰作'},
              {label:'镇馆之宝',value:'波提切利《维纳斯的诞生》（约1485年）和《春》（约1480年）是文艺复兴最著名的画作之一'},
            ],
            description:'乌菲兹的收藏源于美第奇家族数百年的艺术赞助。1737年美第奇家族最后的继承人安娜·玛丽亚·路易莎将整个收藏捐赠给佛罗伦萨人民，条件是永不离开佛罗伦萨。馆内按时间和流派排列，从中世纪金底板画到文艺复兴盛期的杰作，完整呈现了西方艺术从中世纪到现代的演变过程。建议优先参观波提切利厅（第10-14室）和达芬奇厅（第15室）。'
          },
          highlights:['世界最重要美术馆之一！文艺复兴艺术巅峰','波提切利《维纳斯的诞生》《春》','达芬奇、拉斐尔、卡拉瓦乔等大师作品','已预约13:30入场，下午参观人流相对少'],
          warnings:['🟢 已预约5月5日13:30入场','参观约需3-3.5小时，合理分配体力'],photos:['📸 与《维纳斯的诞生》合影'],ticketUrl:'https://www.uffizi.it/en/tickets'}},
      {time:'17:00',type:'sight',title:'🏛️ 领主广场+旧宫',desc:'露天雕塑博物馆，大卫像复制品',
        detail:{emoji:'🏛️',name:'领主广场',subtitle:'Piazza della Signoria · 免费',
          info:[{label:'广场',value:'免费'},{label:'旧宫',value:'需购票'},{label:'用时',value:'30-60分钟'},{label:'亮点',value:'露天雕塑博物馆'}],
          history:{
            summary:'领主广场（Piazza della Signoria）自13世纪起就是佛罗伦萨的政治中心，见证了这座城市最重要的历史事件。',
            facts:[
              {label:'旧宫',value:'韦基奥宫（Palazzo Vecchio）建于1299-1322年，是佛罗伦萨共和国的政府所在地'},
              {label:'大卫像',value:'米开朗基罗的《大卫》原件1504-1873年间矗立于此，现为复制品（原件在学院美术馆）'},
              {label:'兰齐凉廊',value:'1376-1382年建造的开放式拱廊，陈列珀尔修斯斩美杜莎等文艺复兴雕塑杰作'},
              {label:'历史事件',value:'1497年多明我会修士萨伏纳罗拉在此组织"虚荣之火"焚毁艺术品，次年他自己也在此被烧死'},
            ],
            description:'领主广场被誉为"露天雕塑博物馆"。旧宫钟楼高94米，是佛罗伦萨天际线的标志之一。美第奇家族统治佛罗伦萨时期，领主广场是权力展示的舞台。广场地面上有一块圆形铜牌标记了萨伏纳罗拉被处决的位置。海神喷泉（Fontana del Nettuno）由巴尔托洛梅奥·阿曼纳蒂于1565年创作，是佛罗伦萨第一座公共喷泉。'
          },
          highlights:['佛罗伦萨政治中心"露天雕塑博物馆"','大卫雕像复制品、海神喷泉、柯西莫骑马像','兰齐凉廊有珀尔修斯斩美杜莎等雕塑'],warnings:[],photos:['📸 以旧宫钟楼为背景拍广场全景']}},
      {time:'17:30',type:'food',title:'🍦 vivoli / ditta artigianale',desc:'vivoli阿芙佳朵（排最左窗口最快！）液体提拉米苏'},
      {time:'18:00',type:'shopping',title:'🌉 老桥漫步',desc:'日落前的老桥特别美，阿诺河金色水面',
        detail:{emoji:'🌉',name:'老桥',subtitle:'Ponte Vecchio · 免费',
          info:[{label:'门票',value:'免费'},{label:'用时',value:'30分钟'},{label:'特色',value:'桥上珠宝店'}],
          highlights:['佛罗伦萨最著名的桥！桥上全是金银珠宝店','日落前的老桥和阿诺河特别美'],
          warnings:['桥上人很多，注意随身物品'],photos:['📸 在桥上拍阿诺河两岸','📸 从河岸远拍老桥全景']}},
      {time:'19:00',type:'food',title:'🍝 晚餐',desc:'可选天天红中餐馆（川菜想吃辣必去）或当地餐厅'},
    ],
    tips:['周二博物馆全部正常开放，是参观学院美术馆和乌菲兹的最佳日','乌菲兹已预约13:30入场，上午抓紧逛圣母百花+学院美术馆','学院美术馆较小1-1.5小时可看完，为乌菲兹留足时间','佛罗伦萨全程步行穿舒适的鞋！','🍦 路过Venchi一定进！找有巧克力墙那家'],
  },
  {
    id:6, date:'5月6日', weekday:'周三', city:'佛罗伦萨→罗马→✈️', cityTag:'返程',
    title:'返程日', theme:'最后闲逛，买伴手礼，赶飞机',
    emoji:'🛫', color:'#607D8B',
    bannerGradient:'linear-gradient(135deg,#78909C,#455A64)',
    route:['佛罗伦萨闲逛','高铁回罗马','Leonardo Express','FCO机场','22:10航班'],
    mapCenter:[42.8,12.0], mapZoom:7,
    spots:[
      {lat:43.7731,lng:11.2560,name:'佛罗伦萨',num:'❶'},
      {lat:41.9017,lng:12.5020,name:'Roma Termini',num:'❷'},
      {lat:41.8003,lng:12.2389,name:'FCO机场',num:'❸'},
    ],
    timeline:[
      {time:'09:00',type:'default',title:'🌅 最后闲逛/打包',desc:'中央市场买纪念品或再吃个牛肚包'},
      {time:'10:00',type:'shopping',title:'🛍️ 自由活动/补充',desc:'老桥周边逛逛、Venchi买巧克力伴手礼'},
      {time:'12:00',type:'food',title:'🍝 午餐',desc:'最后一顿意大利美食！'},
      {time:'14:30',type:'transport',title:'🚄 高铁回罗马',desc:'约1.5小时到达Roma Termini'},
      {time:'17:00',type:'transport',title:'🚂 Leonardo Express→机场',desc:'€14，32分钟到FCO'},
      {time:'17:35',type:'default',title:'✈️ 机场办理登机/免税店',desc:'预留充足时间，可以最后购物'},
      {time:'22:10',type:'transport',title:'✈️ FCO→DXB→SZX',desc:'5.7 22:40到达深圳，旅途圆满！'},
    ],
    tips:['如想多玩半天可坐更晚火车（17:00-18:00）','建议至少提前3小时到机场','机场免税店可以最后购物'],
  },
];

// ===== 门票数据 =====
const TICKETS_DATA = [
  {name:'🏟️ 罗马斗兽场（联票）',price:'联票€24',advance:'提前2-4周',urgency:'urgent',url:'https://ticketing.colosseo.it/en/',note:'含地下层+竞技场+帕拉丁山+古罗马广场；如抢不到可试意大利语讲解场次'},
  {name:'🎨 梵蒂冈博物馆',price:'在线€25',advance:'提前1-2个月',urgency:'urgent',url:'https://tickets.museivaticani.va/home',note:'已预约16:00入场；精简路线优先看拉奥孔→拉斐尔画室→西斯廷小堂'},
  {name:'🏛️ 万神殿',price:'€5',advance:'提前1-2周',urgency:'urgent',url:'https://portale.museiitaliani.it/b2c/',note:'现场排队半小时以上；最左侧现金最右侧信用卡'},
  {name:'🎨 乌菲兹美术馆',price:'€20-25',advance:'提前2-4周',urgency:'urgent',url:'https://www.uffizi.it/en/tickets',note:'佛罗伦萨最热门景点'},
  {name:'🎨 学院美术馆',price:'€12-16',advance:'提前2-4周',urgency:'urgent',url:'https://www.galleriaaccademiafirenze.it',note:'看大卫真迹'},
  {name:'⛪ 圣母百花穹顶',price:'需购票',advance:'提前1-2周',urgency:'urgent',url:'https://tickets.duomo.firenze.it',note:'教堂免费但穹顶需预约'},
  {name:'🗼 比萨斜塔',price:'需购票',advance:'提前1-2周',urgency:'urgent',url:'在线预订',note:'旺季经常售罄按时段限量'},
  {name:'⛪ 圣彼得大教堂（登穹顶）',price:'步行€5/电梯€8',advance:'建议提前',urgency:'optional',url:'https://booking.basilicasanpietro.va/',note:'教堂免费登顶需票',optional:true},
  {name:'🏰 圣天使城堡',price:'€15',advance:'可现场买',urgency:'optional',url:'',note:'可现场购票',optional:true},
];

// ===== 美食数据 =====
const FOOD_DATA = {
  rome: [
    {emoji:'🍕',name:'Mariuccia',loc:'万神殿附近 · P.za della Cancelleria 92',dish:'本地披萨+开心果火腿披萨',price:'€10-20',rating:'⭐ TOP 1',day:'Day2午餐',
      lat:41.8971,lng:12.4720,address:'P.za della Cancelleria 92, 00186 Roma',
      googleMap:'https://maps.google.com/?q=Mariuccia+Pizzeria+Roma+Piazza+della+Cancelleria',
      reservation:null,reservationNote:'只能walk in，不接受预约'},
    {emoji:'🥩',name:'Saltimbocca ristorante',loc:'罗马',dish:'炖牛尾、鸡尾酒',price:'需预约',rating:'⭐ TOP 2',day:'Day2晚餐',
      lat:41.8960,lng:12.4830,address:'Via di San Nicola da Tolentino 26, 00187 Roma',
      googleMap:'https://maps.google.com/?q=Saltimbocca+Ristorante+Roma',
      reservation:'https://www.thefork.it/',reservationNote:'建议通过TheFork或电话提前预约'},
    {emoji:'🍝',name:'Osteria da Fortunata',loc:'罗马',dish:'Carbonara手工意面',price:'€15-25',rating:'灵魂颤抖',day:'Day1晚餐',
      lat:41.8955,lng:12.4725,address:'Via del Pellegrino 11, 00186 Roma',
      googleMap:'https://maps.google.com/?q=Osteria+da+Fortunata+Via+del+Pellegrino+Roma',
      reservation:null,reservationNote:'人气很旺，建议早点去或到店排队'},
    {emoji:'🍋',name:'Limon\'è',loc:'许愿池附近',dish:'柠檬冰淇淋/雪葩',price:'€5-8',rating:'出片神器',day:'Day1下午',
      lat:41.9006,lng:12.4846,address:'Via del Lavatore 39, 00187 Roma',
      googleMap:'https://maps.google.com/?q=Limon%C3%A8+Roma+Via+del+Lavatore',
      reservation:null,reservationNote:'直接排队购买'},
    {emoji:'🍦',name:'Vitti Roma dal 1898',loc:'西班牙广场附近',dish:'开心果 Gelato',price:'',rating:'百年老店',day:'Day1下午',
      lat:41.9055,lng:12.4827,address:'Piazza di San Lorenzo in Lucina 33, 00186 Roma',
      googleMap:'https://maps.google.com/?q=Vitti+Roma+dal+1898',
      reservation:null,reservationNote:'直接到店'},
    {emoji:'☕',name:'金杯咖啡 Tazza d\'Oro',loc:'万神殿附近',dish:'咖啡沙冰、罗马奶油包',price:'',rating:'百年咖啡店',day:'Day2下午',
      lat:41.8990,lng:12.4781,address:'Via degli Orfani 84, 00186 Roma',
      googleMap:'https://maps.google.com/?q=Tazza+d%27Oro+Roma+Via+degli+Orfani',
      reservation:null,reservationNote:'直接到店'},
    {emoji:'🍕',name:'Trapizzino 三角披萨',loc:'Piazza Trilussa 46',dish:'肉丸红酱、焗烤茄子',price:'€10-20',rating:'特色',day:'备选',
      lat:41.8895,lng:12.4680,address:'Piazza Trilussa 46, 00153 Roma',
      googleMap:'https://maps.google.com/?q=Trapizzino+Piazza+Trilussa+Roma',
      reservation:null,reservationNote:'直接到店'},
  ],
  florence: [
    {emoji:'🥩',name:'牛肚包 da nerbone',loc:'中央市场',dish:'牛肚包（特色！）',price:'',rating:'必吃！',day:'Day5早餐',
      lat:43.7764,lng:11.2534,address:'Mercato Centrale, Piazza del Mercato Centrale, 50123 Firenze',
      googleMap:'https://maps.google.com/?q=Da+Nerbone+Mercato+Centrale+Firenze',
      reservation:null,reservationNote:'市场内摊位，直接排队'},
    {emoji:'🍝',name:'trattoria ZaZa',loc:'佛罗伦萨',dish:'Beef Fillet、龙虾意面',price:'',rating:'⭐⭐⭐⭐⭐',day:'Day5午餐',
      lat:43.7759,lng:11.2530,address:'Piazza del Mercato Centrale 26R, 50123 Firenze',
      googleMap:'https://maps.google.com/?q=Trattoria+ZaZa+Firenze',
      reservation:'https://www.trattoriazaza.it/',reservationNote:'建议官网提前预定'},
    {emoji:'🥪',name:'All\'Antico Vinaio',loc:'市区+火车站分店',dish:'帕尼尼：paradise!、inferno',price:'€5-8',rating:'传奇！',day:'Day4下午',
      lat:43.7691,lng:11.2556,address:'Via dei Neri 74R, 50122 Firenze',
      googleMap:'https://maps.google.com/?q=All%27Antico+Vinaio+Via+dei+Neri+Firenze',
      reservation:null,reservationNote:'排队购买，火车站也有分店不排队'},
    {emoji:'🍕',name:'Giotto Pizzeria',loc:'佛罗伦萨',dish:'米其林合作款 bistecca 披萨',price:'',rating:'本地人推荐',day:'Day3晚餐',
      lat:43.7715,lng:11.2495,address:'Via Ricasoli 30, 50122 Firenze',
      googleMap:'https://maps.google.com/?q=Giotto+Pizzeria+Firenze',
      reservation:null,reservationNote:'可尝试到店或电话预约'},
    {emoji:'🍝',name:'i\'Capaccino',loc:'圣母百花附近',dish:'披萨、千层面',price:'',rating:'不是网红但好吃',day:'Day4晚餐',
      lat:43.7735,lng:11.2548,address:'Via delle Oche 10R, 50122 Firenze',
      googleMap:'https://maps.google.com/?q=i+Capaccino+Firenze+Via+delle+Oche',
      reservation:null,reservationNote:'可直接到店'},
    {emoji:'🍦',name:'vivoli',loc:'佛罗伦萨',dish:'阿芙佳朵、咖啡冰淇淋',price:'',rating:'知名',day:'Day5下午',
      lat:43.7693,lng:11.2601,address:'Via dell\'Isola delle Stinche 7R, 50122 Firenze',
      googleMap:'https://maps.google.com/?q=Vivoli+Gelateria+Firenze',
      reservation:null,reservationNote:'直接到店'},
    {emoji:'☕',name:'ditta artigianale',loc:'佛罗伦萨',dish:'液体提拉米苏咖啡',price:'',rating:'特色咖啡',day:'Day5下午',
      lat:43.7700,lng:11.2515,address:'Via dello Sprone 5R, 50125 Firenze',
      googleMap:'https://maps.google.com/?q=Ditta+Artigianale+Via+dello+Sprone+Firenze',
      reservation:null,reservationNote:'直接到店'},
  ]
};

// ===== Checklist 数据 =====
const CHECKLIST_DATA = [
  '预约 罗马斗兽场 联票（含地下层+竞技场）',
  '预约 梵蒂冈博物馆（建议KLOOK买VIP免排队票）',
  '预约 万神殿 门票',
  '预约 乌菲兹美术馆 门票',
  '预约 学院美术馆 门票',
  '预约 圣母百花大教堂穹顶',
  '预约 比萨斜塔 攀登',
  '购买 罗马→佛罗伦萨 高铁票（5.3 下午）',
  '购买 佛罗伦萨→罗马 高铁票（5.6 下午）',
  '预订罗马住宿（2晚：5.1-5.3）',
  '预订佛罗伦萨住宿（2-3晚：5.3-5.6）',
  '准备 VISA/MASTER 信用卡',
  '下载离线地图（Google Maps）',
  '准备防盗装备（防盗腰包/防盗扣）',
  '打印所有电子门票备份',
  '准备舒适的步行鞋',
];
